name: Azure OIDC Login Test

on:
  workflow_dispatch:   # run manually from GitHub Actions tab

permissions:
  id-token: write
  contents: read

jobs:
  login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify ACR login
        run: |
          az acr login --name "${{ secrets.ACR_NAME }}"
          echo "✅ Successfully logged in to ACR: ${{ secrets.ACR_NAME }}"
